BOT_NAME = "scrapy_trial"
SPIDER_MODULES = ["scrapy_trial.spiders"]
NEWSPIDER_MODULE = "scrapy_trial.spiders"

ROBOTSTXT_OBEY = True
DOWNLOAD_DELAY = 1
CONCURRENT_REQUESTS_PER_DOMAIN = 2
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_TARGET_CONCURRENCY = 2.0